/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.HoaDon_BUS;
import DAO.Laptop_DAO;
import DTO.HoaDon;
import DTO.NhanVien;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ASUS
 */
public class HoaDonBanHang extends javax.swing.JFrame {
    DefaultTableModel model;
    ArrayList<HoaDon> list = new HoaDon_BUS().getAllHoaDon();
    Locale localeVN = new Locale("vi", "VN");
    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    /**
     * Creates new form PhieuNhap
     */
    //Doi tuong thuoc hien chuyen kiem ngay
    DateTimeFormatter ChuyenNgaySQL = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    DateTimeFormatter ChuyenNgayShow = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
    DateFormat ChuyenNgaySQL1 = new SimpleDateFormat("MM/dd/yyyy");
    DateFormat ChuyenNgayShow1 = new SimpleDateFormat("dd/MM/yyyy");
    public static NhanVien NV;

    /**
     * Creates new form NhaCungCap
     */
    public HoaDonBanHang(NhanVien NV) {
        this.NV = NV;
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        model = (DefaultTableModel) tblHoaDon.getModel();
        tblHoaDon.setModel(model);
        txtFind.requestFocus();
        ShowTable();
        
        jpNgayLap.setVisible(false);
        jpTongTien.setVisible(false);
    }
    private void ShowTable(){
        model.setRowCount(0);
        for (HoaDon s : list){
            model.addRow(new Object[]{
                        s.getMaHD(),ChuyenNgayShow.format(s.getNgayLap()),currencyVN.format(s.getTongTien()),s.getSoLuong(),s.getNhanVien(),s.getKhachHang()
                    });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpThanhTieuDe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpKho = new javax.swing.JPanel();
        txtFind = new javax.swing.JTextField();
        btnExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cbxDieuKienLoc = new javax.swing.JComboBox<>();
        jpNgayLap = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateFrom = new com.toedter.calendar.JDateChooser();
        jDateTo = new com.toedter.calendar.JDateChooser();
        btnNgayLap = new javax.swing.JButton();
        jpTongTien = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        btnTongTien = new javax.swing.JButton();
        btnChiTietHoaDon = new javax.swing.JButton();
        jpMenu1 = new javax.swing.JPanel();
        lblAvatar1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblChucVu1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblKhoHang1 = new javax.swing.JLabel();
        lblNhapHang1 = new javax.swing.JLabel();
        lblBanHang7 = new javax.swing.JLabel();
        lblBanHang8 = new javax.swing.JLabel();
        lblBanHang9 = new javax.swing.JLabel();
        lblBanHang10 = new javax.swing.JLabel();
        lblBanHang11 = new javax.swing.JLabel();
        lblBanHang12 = new javax.swing.JLabel();
        lblBanHang13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(1500, 740));

        jpThanhTieuDe.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỆ THỐNG QUẢN LÝ CỬA HÀNG LAPTOP");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/LOGO.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Profile.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Logout.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpThanhTieuDeLayout = new javax.swing.GroupLayout(jpThanhTieuDe);
        jpThanhTieuDe.setLayout(jpThanhTieuDeLayout);
        jpThanhTieuDeLayout.setHorizontalGroup(
            jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThanhTieuDeLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1016, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(12, 12, 12))
        );
        jpThanhTieuDeLayout.setVerticalGroup(
            jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThanhTieuDeLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpThanhTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        jpKho.setBackground(new java.awt.Color(255, 255, 255));

        txtFind.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFind.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Excel.png"))); // NOI18N
        btnExcel.setText("Xuất file excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Ngày lập", "Tổng tiền", "Số lượng", "Nhân viên", "Khách hàng"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Điều kiện lọc:");

        cbxDieuKienLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định", "Mã hoá đơn", "Ngày lập", "Tổng tiền", "Số lượng", "Nhân viên", "Khách hàng", " ", " " }));
        cbxDieuKienLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDieuKienLocActionPerformed(evt);
            }
        });

        jpNgayLap.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Từ :");

        jLabel9.setText("Đến : ");

        btnNgayLap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNgayLap.setText("Lọc");
        btnNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgayLapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpNgayLapLayout = new javax.swing.GroupLayout(jpNgayLap);
        jpNgayLap.setLayout(jpNgayLapLayout);
        jpNgayLapLayout.setHorizontalGroup(
            jpNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNgayLapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNgayLapLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(jpNgayLapLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNgayLap)
                .addGap(12, 12, 12))
        );
        jpNgayLapLayout.setVerticalGroup(
            jpNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNgayLapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNgayLapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpTongTien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Từ :");

        txtFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromActionPerformed(evt);
            }
        });

        jLabel11.setText("Đến : ");

        btnTongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTongTien.setText("Lọc");
        btnTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTongTienLayout = new javax.swing.GroupLayout(jpTongTien);
        jpTongTien.setLayout(jpTongTienLayout);
        jpTongTienLayout.setHorizontalGroup(
            jpTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTongTienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpTongTienLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTongTienLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTongTienLayout.setVerticalGroup(
            jpTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTongTienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTongTienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        btnChiTietHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Excel.png"))); // NOI18N
        btnChiTietHoaDon.setText("Xem chi tiết");
        btnChiTietHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpKhoLayout = new javax.swing.GroupLayout(jpKho);
        jpKho.setLayout(jpKhoLayout);
        jpKhoLayout.setHorizontalGroup(
            jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpKhoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDieuKienLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChiTietHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(jpKhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpKhoLayout.setVerticalGroup(
            jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKhoLayout.createSequentialGroup()
                .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpKhoLayout.createSequentialGroup()
                        .addComponent(btnExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChiTietHoaDon))
                    .addComponent(jpNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpKhoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpKhoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxDieuKienLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        jpMenu1.setBackground(new java.awt.Color(255, 255, 255));

        lblAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Avatar.png"))); // NOI18N

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName1.setText("Lê Hoài Nam");

        lblChucVu1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblChucVu1.setText("Quản lý");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Line.png"))); // NOI18N

        lblKhoHang1.setBackground(new java.awt.Color(255, 255, 255));
        lblKhoHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhoHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KhoHang.png"))); // NOI18N
        lblKhoHang1.setText("Kho hàng");
        lblKhoHang1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKhoHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhoHang1MouseClicked(evt);
            }
        });

        lblNhapHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNhapHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhapHang.png"))); // NOI18N
        lblNhapHang1.setText("Nhập hàng");
        lblNhapHang1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhapHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhapHang1MouseClicked(evt);
            }
        });

        lblBanHang7.setBackground(new java.awt.Color(102, 204, 255));
        lblBanHang7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/BanHang.png"))); // NOI18N
        lblBanHang7.setText("Bán hàng");
        lblBanHang7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang7MouseClicked(evt);
            }
        });

        lblBanHang8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhanVien.png"))); // NOI18N
        lblBanHang8.setText("Nhân viên");
        lblBanHang8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang8MouseClicked(evt);
            }
        });

        lblBanHang9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KhachHang.png"))); // NOI18N
        lblBanHang9.setText("Khách hàng");
        lblBanHang9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang9MouseClicked(evt);
            }
        });

        lblBanHang10.setBackground(new java.awt.Color(102, 204, 255));
        lblBanHang10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhaCungCap.png"))); // NOI18N
        lblBanHang10.setText("Nhà cung cấp");
        lblBanHang10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang10MouseClicked(evt);
            }
        });

        lblBanHang11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PhieuNhapHang_1.png"))); // NOI18N
        lblBanHang11.setText("Phiếu nhập hàng");
        lblBanHang11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang11MouseClicked(evt);
            }
        });

        lblBanHang12.setBackground(new java.awt.Color(102, 204, 255));
        lblBanHang12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Bill.png"))); // NOI18N
        lblBanHang12.setText("Hóa đơn bán hàng");
        lblBanHang12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang12.setOpaque(true
        );
        lblBanHang12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang12MouseClicked(evt);
            }
        });

        lblBanHang13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Thống kê.png"))); // NOI18N
        lblBanHang13.setText("Thống kê doanh thu");
        lblBanHang13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenu1Layout = new javax.swing.GroupLayout(jpMenu1);
        jpMenu1.setLayout(jpMenu1Layout);
        jpMenu1Layout.setHorizontalGroup(
            jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenu1Layout.createSequentialGroup()
                .addGroup(jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBanHang9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNhapHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKhoHang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpMenu1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenu1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblChucVu1)
                .addGap(76, 76, 76))
        );
        jpMenu1Layout.setVerticalGroup(
            jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenu1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblAvatar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKhoHang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNhapHang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang13)
                .addGap(0, 87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpThanhTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpThanhTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jpMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        String path=null,tenfile=null;
        boolean flag;
        do{
            flag=false;
            tenfile = JOptionPane.showInputDialog("Nhập tên file :");
            if(tenfile == null){
                return;
            }
            if(tenfile.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập tên file");
                flag=true;
            }
            else if (tenfile.contains(" ")){
                JOptionPane.showMessageDialog(rootPane, "Tên file không có khoảng trắng");
                flag=true;
            }
            else if (tenfile.contains("/") || tenfile.contains("%") || tenfile.contains("#") || tenfile.contains(":") ||tenfile.contains(";") ||tenfile.contains("~") ||tenfile.contains(".") ){
                JOptionPane.showMessageDialog(rootPane, "Tên file không chứa kí tự đặc biệt");
                flag=true;
            }
        }
        while(flag);
        
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if(x == JFileChooser.APPROVE_OPTION){
            path=j.getSelectedFile().getPath()+"//"+tenfile;
        }
        FileOutputStream file;

        XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet Sheet = wb.createSheet("HoaDon");
        XSSFRow row = null;
        Cell cell = null;
        row = Sheet.createRow(0);
        
        cell = row.createCell(0, CellType.STRING);
        cell.setCellValue("Mã hóa đơn");
        cell = row.createCell(1, CellType.STRING);
        cell.setCellValue("Ngày lập");
        cell = row.createCell(2, CellType.STRING);
        cell.setCellValue("Tổng tiền");
        cell = row.createCell(3, CellType.STRING);
        cell.setCellValue("Số lượng");
        cell = row.createCell(4, CellType.STRING);
        cell.setCellValue("Nhân viên");
        cell = row.createCell(5, CellType.STRING);
        cell.setCellValue("Khách hàng");
        
        for(int i=0;i<tblHoaDon.getRowCount();i++) {
            row = Sheet.createRow(i+1);
            cell = row.createCell(0, CellType.NUMERIC);
            cell.setCellValue((int)tblHoaDon.getValueAt(i, 0));
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue(tblHoaDon.getValueAt(i, 1).toString());
            cell = row.createCell(2, CellType.NUMERIC);
            cell.setCellValue((int) tblHoaDon.getValueAt(i, 2));
            cell = row.createCell(3, CellType.NUMERIC);
            cell.setCellValue((int) tblHoaDon.getValueAt(i, 3));
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue( tblHoaDon.getValueAt(i, 4).toString());
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue( tblHoaDon.getValueAt(i, 5).toString());
        }
        try {
            file = new FileOutputStream(path+".xlsx");
            wb.write(file);
            wb.close();
            file.close();

        } catch (IOException ex) {
            Logger.getLogger(Laptop_DAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(path != null){
            JOptionPane.showMessageDialog(rootPane, "Xuất file Excel thành công");
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lblKhoHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoHang1MouseClicked
        new KhoHang(NV).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblKhoHang1MouseClicked

    private void lblNhapHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapHang1MouseClicked
        new NhapHang(NV).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblNhapHang1MouseClicked

    private void lblBanHang7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang7MouseClicked
        // TODO add your handling code here:
        new BanHang(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang7MouseClicked

    private void lblBanHang8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang8MouseClicked
        new QuanLyNhanVienVaTaiKhoan(NV).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblBanHang8MouseClicked

    private void lblBanHang9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang9MouseClicked
        new QuanLyKhachHang(NV).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblBanHang9MouseClicked

    private void lblBanHang10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang10MouseClicked
        new NhaCungCap(NV).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblBanHang10MouseClicked

    private void lblBanHang11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang11MouseClicked
        new PhieuNhapHang(NV).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblBanHang11MouseClicked

    private void lblBanHang12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang12MouseClicked
        new HoaDonBanHang(NV).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblBanHang12MouseClicked

    private void lblBanHang13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang13MouseClicked
        new ThongKe(NV).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblBanHang13MouseClicked

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    private void cbxDieuKienLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDieuKienLocActionPerformed

        if(cbxDieuKienLoc.getSelectedItem() == "Ngày lập"){
            txtFind.setEnabled(false);
            jpNgayLap.setVisible(true);
            jpTongTien.setVisible(false);
            txtFrom.setText("");
            txtTo.setText("");

        }
        else if(cbxDieuKienLoc.getSelectedItem() == "Tổng tiền"){
            txtFind.setEnabled(false);
            jpNgayLap.setVisible(false);
            jpTongTien.setVisible(true);
            jDateFrom.setDate(null);
            jDateTo.setDate(null);

        }
        else{
            txtFind.setEnabled(true);
            jpNgayLap.setVisible(false);
            jpTongTien.setVisible(false);
            jDateFrom.setDate(null);
            jDateTo.setDate(null);
            txtFrom.setText("");
            txtTo.setText("");

        }
        txtFind.setText("");
        txtFind.requestFocus();
        ShowTable();
    }//GEN-LAST:event_cbxDieuKienLocActionPerformed

    private void btnNgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgayLapActionPerformed
        // TODO add your handling code here:
        if(jDateFrom.getDate() == null || jDateTo.getDate()==null){
            JOptionPane.showMessageDialog(rootPane, "Không để trống lựa chọn");
            return;
        }
        Date From = jDateFrom.getDate();
        Date To = jDateTo.getDate();
        String From_str = ChuyenNgaySQL1.format(From);
        String To_str = ChuyenNgaySQL1.format(To);
        model.setRowCount(0);
        ArrayList<HoaDon> list_find = new HoaDon_BUS().getListTimKiem("NgayLap",From_str,To_str);
        for(HoaDon s : list_find){
            model.addRow(new Object[]{
                s.getMaHD(),ChuyenNgayShow.format(s.getNgayLap()),currencyVN.format(s.getTongTien()),s.getSoLuong(),s.getNhanVien(),s.getKhachHang()
            });
        }
    }//GEN-LAST:event_btnNgayLapActionPerformed

    private void btnTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongTienActionPerformed
        // TODO add your handling code here:
        String From = txtFrom.getText();
        String To = txtTo.getText();
        if(From.isEmpty() || To.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Không để trống thông tin");
        }
        try{
            int From_int = Integer.parseInt(From);
            int To_int = Integer.parseInt(To);
            if(From_int < 0 || To_int < 0){
                JOptionPane.showMessageDialog(rootPane, "Giá tiền phải lớn hơn 0");
                return;
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Chỉ nhập số");
            return;
        }
        model.setRowCount(0);
        ArrayList<HoaDon> list_find = new HoaDon_BUS().getListTimKiem("TongTien",From,To);
        for(HoaDon s : list_find){
            model.addRow(new Object[]{
                s.getMaHD(),ChuyenNgayShow.format(s.getNgayLap()),currencyVN.format(s.getTongTien()),s.getSoLuong(),s.getNhanVien(),s.getKhachHang()
            });
        }
    }//GEN-LAST:event_btnTongTienActionPerformed

    private void btnChiTietHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietHoaDonActionPerformed
        String str=txtFind.getText();
        String ngaylap,nv,kh;
        int sl,tongtien;
        int row = tblHoaDon.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 dòng rồi nhấn nút xem chi tiết!");
            return;
        }
        else{
            ngaylap=(String) tblHoaDon.getValueAt(row, 1);
            tongtien = (int) tblHoaDon.getValueAt(row, 2);
            sl = (int) tblHoaDon.getValueAt(row, 3);
            nv = (String) tblHoaDon.getValueAt(row, 4);
            kh = (String) tblHoaDon.getValueAt(row, 5);
            ChiTietHoaDon a = new ChiTietHoaDon(Integer.parseInt(str),ngaylap,tongtien,sl,nv,kh);
            a.setVisible(true);
            a.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnChiTietHoaDonActionPerformed

    private void txtFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromActionPerformed

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        // TODO add your handling code here:
                // TODO add your handling code here:
        String cbx_DK = (String) cbxDieuKienLoc.getSelectedItem();
        String find = txtFind.getText();
        model.setRowCount(0);
        switch(cbx_DK){
            case "Mã hóa đơn":{
                for (HoaDon s : list){
                    if(Integer.toString(s.getMaHD()).contains(find)){
                        model.addRow(new Object[]{
                            s.getMaHD(),ChuyenNgayShow.format(s.getNgayLap()),currencyVN.format(s.getTongTien()),s.getSoLuong(),s.getNhanVien(),s.getKhachHang()
                        });
                    }
                }
                break;
            }
            case "Số lượng":{
                for (HoaDon s : list){
                    if(Integer.toString(s.getSoLuong()).equals(find)){
                        model.addRow(new Object[]{
                           s.getMaHD(),ChuyenNgayShow.format(s.getNgayLap()),currencyVN.format(s.getTongTien()),s.getSoLuong(),s.getNhanVien(),s.getKhachHang()
                        });
                    }
                }
                break;
            }
            case "Nhân viên":{
                for (HoaDon s : list){
                    if(s.getNhanVien().equals(find)){
                        model.addRow(new Object[]{
                           s.getMaHD(),ChuyenNgayShow.format(s.getNgayLap()),currencyVN.format(s.getTongTien()),s.getSoLuong(),s.getNhanVien(),s.getKhachHang()
                        });
                    }
                }
                break;
            }
            case "Khách hàng":{
                for (HoaDon s : list){
                    if(s.getKhachHang().equals(find)){
                        model.addRow(new Object[]{
                           s.getMaHD(),ChuyenNgayShow.format(s.getNgayLap()),currencyVN.format(s.getTongTien()),s.getSoLuong(),s.getNhanVien(),s.getKhachHang()
                        });
                    }
                }
                break;
            }
            default :{
                for (HoaDon s : list){
                    if(Integer.toString(s.getMaHD()).contains(find)  || ChuyenNgayShow.format(s.getNgayLap()).contains(find) || Integer.toString(s.getTongTien()).contains(find) || Integer.toString(s.getSoLuong()).contains(find) || s.getNhanVien().contains(find) || s.getKhachHang().contains(find)){
                        model.addRow(new Object[]{
                            s.getMaHD(),ChuyenNgayShow.format(s.getNgayLap()),currencyVN.format(s.getTongTien()),s.getSoLuong(),s.getNhanVien(),s.getKhachHang()
                        });
                    }
                }
                break;
            }
        }

    }//GEN-LAST:event_txtFindKeyReleased

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int Selected_Row = tblHoaDon.getSelectedRow();
        txtFind.setText(Integer.toString((int) tblHoaDon.getValueAt(Selected_Row, 0)));

    }//GEN-LAST:event_tblHoaDonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonBanHang(NV).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTietHoaDon;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnNgayLap;
    private javax.swing.JButton btnTongTien;
    private javax.swing.JComboBox<String> cbxDieuKienLoc;
    private com.toedter.calendar.JDateChooser jDateFrom;
    private com.toedter.calendar.JDateChooser jDateTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpKho;
    private javax.swing.JPanel jpMenu1;
    private javax.swing.JPanel jpNgayLap;
    private javax.swing.JPanel jpThanhTieuDe;
    private javax.swing.JPanel jpTongTien;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblBanHang10;
    private javax.swing.JLabel lblBanHang11;
    private javax.swing.JLabel lblBanHang12;
    private javax.swing.JLabel lblBanHang13;
    private javax.swing.JLabel lblBanHang7;
    private javax.swing.JLabel lblBanHang8;
    private javax.swing.JLabel lblBanHang9;
    private javax.swing.JLabel lblChucVu1;
    private javax.swing.JLabel lblKhoHang1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblNhapHang1;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
