/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.ChiTietLaptop_BUS;
import BUS.Laptop_BUS;
import BUS.TaiKhoan_BUS;
import DAO.Laptop_DAO;
import DTO.ChiTietLaptop;
import DTO.Laptop;
import DTO.NhanVien;
import DTO.TaiKhoan;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ASUS
 */
public class KhoHang extends javax.swing.JFrame {
    DefaultTableModel model1,model2;
    ArrayList<Laptop> list1;
    ArrayList<ChiTietLaptop> list2;
    
    public static NhanVien NV;
    public TaiKhoan TK;
    /**
     * Creates new form KhoHang
     */
    public KhoHang(NhanVien NV) {
        
        this.NV = NV;
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        model1 = (DefaultTableModel) tblLaptop.getModel();
        model2 = (DefaultTableModel) tblCTLaptop.getModel();
        tblLaptop.setModel(model1);
        tblCTLaptop.setModel(model2);
        tblCTLaptop.setEnabled(false);
        
        list1 = new Laptop_BUS().getAllLaptop();
        list2 = new ChiTietLaptop_BUS().getListChiTietLaptop();
        ShowTable1();
        ShowTable2();
        
        // Tìm thông tin nhân viên vừa đăng nhập
        TimTaiKhoan(NV);
        
    }
    public void TimTaiKhoan(NhanVien NV){
        List<TaiKhoan> list_TaiKhoan = new TaiKhoan_BUS().getListTaiKhoan();
        for(TaiKhoan tk : list_TaiKhoan){
            if (tk.getTenDN().equals(NV.getMaNV())){
                TK = tk;
                lblName.setText(NV.getTenNV());
                lblChucVu.setText(TK.getPhanQuyen());
                return;
            }
        }
    }
    
    
    public void ShowTable1(){
        model1.setRowCount(0);
        list1 = new Laptop_BUS().getAllLaptop();
        for (Laptop s : list1) {
            if(s.getTrangThai().equals("0")){
                continue;
            }
            model1.addRow(new Object[]{
                s.getID(), s.getTen(), s.getSoLuongTonKho(), s.getGia(), s.getCPU(), s.getRAM(), s.getGPU(),
            });
        }
    }
    public void ShowTable2(){
        model2.setRowCount(0);
        list2 = new ChiTietLaptop_BUS().getListChiTietLaptop();
        for (ChiTietLaptop s : list2) {
            if(s.getTrangThai().equals("0")){
                continue;
            }
            model2.addRow(new Object[]{
                s.getIDRieng(), s.getNgayNhap(), s.getMauLapTop()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpThanhTieuDe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpKho = new javax.swing.JPanel();
        txtFind = new javax.swing.JTextField();
        lbTimKiem = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaptop = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTLaptop = new javax.swing.JTable();
        jpMenu1 = new javax.swing.JPanel();
        lblAvatar1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblKhoHang1 = new javax.swing.JLabel();
        lblNhapHang1 = new javax.swing.JLabel();
        lblBanHang7 = new javax.swing.JLabel();
        lblBanHang8 = new javax.swing.JLabel();
        lblBanHang9 = new javax.swing.JLabel();
        lblBanHang10 = new javax.swing.JLabel();
        lblBanHang11 = new javax.swing.JLabel();
        lblBanHang12 = new javax.swing.JLabel();
        lblBanHang13 = new javax.swing.JLabel();
        lblBanHang16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpThanhTieuDe.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỆ THỐNG QUẢN LÝ CỬA HÀNG LAPTOP");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/LOGO.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Profile.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Logout.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpThanhTieuDeLayout = new javax.swing.GroupLayout(jpThanhTieuDe);
        jpThanhTieuDe.setLayout(jpThanhTieuDeLayout);
        jpThanhTieuDeLayout.setHorizontalGroup(
            jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThanhTieuDeLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(12, 12, 12))
        );
        jpThanhTieuDeLayout.setVerticalGroup(
            jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThanhTieuDeLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpThanhTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpKho.setBackground(new java.awt.Color(255, 255, 255));

        txtFind.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFind.setText("Nhập thông tin tìm kiếm");
        txtFind.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        lbTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/TimKiem.png"))); // NOI18N

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Sửa.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Excel.png"))); // NOI18N
        btnExcel.setText("Xuất file excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        tblLaptop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Số lượng tồn kho", "Giá", "CPU", "RAM", "GPU"
            }
        ));
        tblLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaptopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLaptop);

        tblCTLaptop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID riêng", "Ngày nhập", "Mẫu Laptop"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCTLaptop);

        javax.swing.GroupLayout jpKhoLayout = new javax.swing.GroupLayout(jpKho);
        jpKho.setLayout(jpKhoLayout);
        jpKhoLayout.setHorizontalGroup(
            jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKhoLayout.createSequentialGroup()
                .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpKhoLayout.createSequentialGroup()
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTimKiem))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addGroup(jpKhoLayout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnExcel)
                        .addGap(34, 34, 34))))
        );
        jpKhoLayout.setVerticalGroup(
            jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKhoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFind)
                    .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        jpMenu1.setBackground(new java.awt.Color(255, 255, 255));

        lblAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Avatar.png"))); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Lê Hoài Nam");

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblChucVu.setText("Quản lý");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Line.png"))); // NOI18N

        lblKhoHang1.setBackground(new java.awt.Color(102, 204, 255));
        lblKhoHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhoHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KhoHang.png"))); // NOI18N
        lblKhoHang1.setText("Kho hàng");
        lblKhoHang1.setOpaque(true
        );
        lblKhoHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhoHang1MouseClicked(evt);
            }
        });

        lblNhapHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNhapHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhapHang.png"))); // NOI18N
        lblNhapHang1.setText("Nhập hàng");
        lblNhapHang1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhapHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhapHang1MouseClicked(evt);
            }
        });

        lblBanHang7.setBackground(new java.awt.Color(102, 204, 255));
        lblBanHang7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/BanHang.png"))); // NOI18N
        lblBanHang7.setText("Bán hàng");
        lblBanHang7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang7MouseClicked(evt);
            }
        });

        lblBanHang8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhanVien.png"))); // NOI18N
        lblBanHang8.setText("Nhân viên");
        lblBanHang8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang8MouseClicked(evt);
            }
        });

        lblBanHang9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KhachHang.png"))); // NOI18N
        lblBanHang9.setText("Khách hàng");
        lblBanHang9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang9MouseClicked(evt);
            }
        });

        lblBanHang10.setBackground(new java.awt.Color(102, 204, 255));
        lblBanHang10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhaCungCap.png"))); // NOI18N
        lblBanHang10.setText("Nhà cung cấp");
        lblBanHang10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang10MouseClicked(evt);
            }
        });

        lblBanHang11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PhieuNhapHang_1.png"))); // NOI18N
        lblBanHang11.setText("Phiếu nhập hàng");
        lblBanHang11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang11MouseClicked(evt);
            }
        });

        lblBanHang12.setBackground(new java.awt.Color(102, 204, 255));
        lblBanHang12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Bill.png"))); // NOI18N
        lblBanHang12.setText("Hóa đơn bán hàng");
        lblBanHang12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang12MouseClicked(evt);
            }
        });

        lblBanHang13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Thống kê.png"))); // NOI18N
        lblBanHang13.setText("Thống kê doanh thu");
        lblBanHang13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang13MouseClicked(evt);
            }
        });

        lblBanHang16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/user.png"))); // NOI18N
        lblBanHang16.setText("Tài khoản");
        lblBanHang16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenu1Layout = new javax.swing.GroupLayout(jpMenu1);
        jpMenu1.setLayout(jpMenu1Layout);
        jpMenu1Layout.setHorizontalGroup(
            jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenu1Layout.createSequentialGroup()
                .addGroup(jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBanHang9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNhapHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKhoHang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpMenu1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenu1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblChucVu)
                .addGap(76, 76, 76))
            .addGroup(jpMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBanHang16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpMenu1Layout.setVerticalGroup(
            jpMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenu1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblAvatar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKhoHang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNhapHang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpThanhTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpThanhTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String str=txtFind.getText();
        int row = tblLaptop.getSelectedRow();
        if (row == -1 ){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 dòng rồi nhấn nút xoá!");
            return;
        }
        else{
            if((int)tblLaptop.getValueAt(row, 2) != 0){
                JOptionPane.showMessageDialog(rootPane, "Laptop đang có hàng trong kho. Không thể xóa!");
                return ;
            }
            int dk=JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa" , "Confirm", JOptionPane.YES_NO_OPTION);
            if(dk!=JOptionPane.YES_OPTION){
                return;
            }
            if(new Laptop_DAO().deleteLaptop((String) tblLaptop.getValueAt(row, 0))){
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công!");
                list1 = new Laptop_DAO().getListLaptop();
                txtFind.setText("");
                ShowTable1();
                return ;
            }

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String str;
        boolean flag = false;
        do{
            flag = false;
            str = JOptionPane.showInputDialog("Nhập id: ");
            if(str == null){
                txtFind.requestFocus();
                return;
            }
            if (str.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Chưa nhập id!");
                flag = true;
            }

            for(Laptop s : list1){
                if(s.getID().equals(str) && s.getTrangThai().equals("1")){
                    JOptionPane.showMessageDialog(this, "Id đã tồn tại!");
                    flag = true;
                }
            }
        }
        while (flag);
        NhapThongTinLaptop a = new NhapThongTinLaptop(str);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        a.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                ShowTable1();
            }
        });
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        String str=txtFind.getText();
        int row = tblLaptop.getSelectedRow();
        if (row == -1 ){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 dòng rồi nhấn nút sửa!");
            return;
        }
        else{
            SuaThongTinLaptop a = new SuaThongTinLaptop(str);
            a.setVisible(true);
            a.setLocationRelativeTo(null);
            a.addWindowListener(new WindowAdapter() {
                public void windowClosed(WindowEvent e) {
                    ShowTable1();
                }
            });
        }
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        String path=null,tenfile=null;
        boolean flag;
        do{
            flag=false;
            tenfile = JOptionPane.showInputDialog("Nhập tên file :");
            if(tenfile == null){
                return;
            }
            if(tenfile.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập tên file");
                flag=true;
            }
            else if (tenfile.contains(" ")){
                JOptionPane.showMessageDialog(rootPane, "Tên file không có khoảng trắng");
                flag=true;
            }
            else if (tenfile.contains("/") || tenfile.contains("%") || tenfile.contains("#") || tenfile.contains(":") ||tenfile.contains(";") ||tenfile.contains("~") ||tenfile.contains(".") ){
                JOptionPane.showMessageDialog(rootPane, "Tên file không chứa kí tự đặc biệt");
                flag=true;
            }
        }
        while(flag);
        
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if(x == JFileChooser.APPROVE_OPTION){
            path=j.getSelectedFile().getPath()+"//"+tenfile;
        }
        FileOutputStream file;

        XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet Sheet = wb.createSheet("KhoLaptop");
        XSSFRow row = null;
        Cell cell = null;
        row = Sheet.createRow(0);
        
        cell = row.createCell(0, CellType.STRING);
        cell.setCellValue("ID");
        cell = row.createCell(1, CellType.STRING);
        cell.setCellValue("Tên");
        cell = row.createCell(2, CellType.STRING);
        cell.setCellValue("Số lượng tồn kho");
        cell = row.createCell(3, CellType.STRING);
        cell.setCellValue("Giá");
        cell = row.createCell(4, CellType.STRING);
        cell.setCellValue("CPU");
        cell = row.createCell(5, CellType.STRING);
        cell.setCellValue("RAM");
        cell = row.createCell(6, CellType.STRING);
        cell.setCellValue("GPU");
        cell = row.createCell(7, CellType.STRING);
        cell.setCellValue("  ");
        cell = row.createCell(8, CellType.STRING);
        cell.setCellValue("ID riêng");
        cell = row.createCell(9, CellType.STRING);
        cell.setCellValue("Ngày lập");
        cell = row.createCell(10, CellType.STRING);
        cell.setCellValue("Mẫu laptop");
        
        for(int i=0;i<tblLaptop.getRowCount();i++) {
            row = Sheet.createRow(i+1);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue(tblLaptop.getValueAt(i, 0).toString());
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue(tblLaptop.getValueAt(i, 1).toString());
            cell = row.createCell(2, CellType.NUMERIC);
            cell.setCellValue((int) tblLaptop.getValueAt(i, 2));
            cell = row.createCell(3, CellType.NUMERIC);
            cell.setCellValue((int) tblLaptop.getValueAt(i, 3));
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue(tblLaptop.getValueAt(i, 4).toString());
            cell = row.createCell(5, CellType.NUMERIC);
            cell.setCellValue((int) tblLaptop.getValueAt(i, 5));
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue(tblLaptop.getValueAt(i, 6).toString());
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue(" ");
            cell = row.createCell(8, CellType.STRING);
            cell.setCellValue(tblCTLaptop.getValueAt(i, 0).toString());
            cell = row.createCell(9, CellType.STRING);
            cell.setCellValue(tblCTLaptop.getValueAt(i, 1).toString());
            cell = row.createCell(10, CellType.STRING);
            cell.setCellValue(tblCTLaptop.getValueAt(i, 2).toString());
        }
        try {
            file = new FileOutputStream(path+".xlsx");
            wb.write(file);
            wb.close();
            file.close();

        } catch (IOException ex) {
            Logger.getLogger(Laptop_DAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(path != null){
            JOptionPane.showMessageDialog(rootPane, "Xuất file Excel thành công");
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void tblLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaptopMouseClicked
        // TODO add your handling code here:
        int selectedrow = tblLaptop.getSelectedRow();

        txtFind.setText((String) tblLaptop.getValueAt(selectedrow, 0));
    }//GEN-LAST:event_tblLaptopMouseClicked

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        // TODO add your handling code here:
        model1.setRowCount(0);
        String find = txtFind.getText();

        for(Laptop s : list1){
            if(s.getTen()==null){
                continue;
            }
            if(s.getID().contains(find) || s.getTen().contains(find) || String.valueOf(s.getSoLuongTonKho()).contains(find) || s.getCPU().contains(find)
                || String.valueOf(s.getRAM()).contains(find) || s.getGPU().contains(find) || s.getTrangThai().contains(find)){
                model1.addRow(new Object[]{
                    s.getID(), s.getTen(), s.getSoLuongTonKho(), s.getCPU(), s.getRAM(), s.getGPU(), s.getTrangThai()
                });
            }
        }
    }//GEN-LAST:event_txtFindKeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lblKhoHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoHang1MouseClicked
        new KhoHang(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblKhoHang1MouseClicked

    private void lblNhapHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapHang1MouseClicked
        new NhapHang(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNhapHang1MouseClicked

    private void lblBanHang7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang7MouseClicked
        // TODO add your handling code here:
        new BanHang(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang7MouseClicked

    private void lblBanHang8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang8MouseClicked
        new QuanLyNhanVien(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang8MouseClicked

    private void lblBanHang9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang9MouseClicked
        new QuanLyKhachHang(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang9MouseClicked

    private void lblBanHang10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang10MouseClicked
        new QuanLyNhaCungCap(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang10MouseClicked

    private void lblBanHang11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang11MouseClicked
        new PhieuNhapHang(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang11MouseClicked

    private void lblBanHang12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang12MouseClicked
        new HoaDonBanHang(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang12MouseClicked

    private void lblBanHang13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang13MouseClicked
        new ThongKe(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang13MouseClicked

    private void lblBanHang16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang16MouseClicked
        // TODO add your handling code here:
        new QuanLyTaiKhoan(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoHang(NV).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpKho;
    private javax.swing.JPanel jpMenu1;
    private javax.swing.JPanel jpThanhTieuDe;
    private javax.swing.JLabel lbTimKiem;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblBanHang10;
    private javax.swing.JLabel lblBanHang11;
    private javax.swing.JLabel lblBanHang12;
    private javax.swing.JLabel lblBanHang13;
    private javax.swing.JLabel lblBanHang16;
    private javax.swing.JLabel lblBanHang7;
    private javax.swing.JLabel lblBanHang8;
    private javax.swing.JLabel lblBanHang9;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblKhoHang1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNhapHang1;
    private javax.swing.JTable tblCTLaptop;
    private javax.swing.JTable tblLaptop;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
