/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.KhachHang_BUS;
import DTO.KhachHang;
import GUI.QuanLyKhachHang;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author luugi
 */
public class ModifyUser extends javax.swing.JFrame {

    /**
     * Creates new form addUser
     */
    public ModifyUser() {
        initComponents();
        txtStatus.setText("1"); // Set default value for "Trạng Thái"
        txtPoint.setText("0");  // Set default value for "Điểm Thưởng"
        button1.setEnabled(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

    }

    ModifyUser(QuanLyKhachHang aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

       ModifyUser(QuanLyKhachHang qlkh, boolean b, String maKH, String tenKH, String sdt, String diachi, String trangThai, String tienthuong) {
    initComponents();
    this.qlkh = qlkh; 

        // Set the received data to the input fields
        txtMAKH.setText(maKH);
        txtTENKH.setText(tenKH);
        txtSDT.setText(sdt);
        txtAddress.setText(diachi);
        txtStatus.setText(trangThai);
        txtPoint.setText(tienthuong);
        button2.setEnabled(false);
        txtMAKH.setEnabled(false);

        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTENKH = new java.awt.TextField();
        txtMAKH = new java.awt.TextField();
        txtSDT = new java.awt.TextField();
        txtAddress = new java.awt.TextField();
        txtStatus = new java.awt.TextField();
        txtPoint = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" Khách Hàng");

        jLabel2.setText("Mã KH:");

        jLabel3.setText("Địa chỉ:");

        jLabel6.setText("Điểm Thưởng:");

        jLabel7.setText("SDT KH:");

        jLabel8.setText("Tên KH:");

        jLabel9.setText("Trạng Thái:");

        txtTENKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTENKHActionPerformed(evt);
            }
        });

        txtMAKH.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMAKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMAKHActionPerformed(evt);
            }
        });

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        txtPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPointActionPerformed(evt);
            }
        });

        button1.setLabel("Save");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("Create");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTENKH, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))))
                .addContainerGap(477, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTENKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        button1.getAccessibleContext().setAccessibleName("Luu_btn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
          try {
        String maKH = txtMAKH.getText();
        String tenKH = txtTENKH.getText();
        String sdtKH = txtSDT.getText();
        String diaChi = txtAddress.getText();
        String trangThai = txtStatus.getText();
        String diemThuong = txtPoint.getText();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);


        // Debugging statements
        System.out.println("maKH: " + maKH);
        System.out.println("tenKH: " + tenKH);
        System.out.println("sdtKH: " + sdtKH);
        System.out.println("diaChi: " + diaChi);
        System.out.println("trangThai: " + trangThai);
        System.out.println("diemThuong: " + diemThuong);

        KhachHang kh = new KhachHang();
        kh.setMaKH(maKH);
        kh.setTen(tenKH);
        kh.setSDT(sdtKH);
        kh.setDiaChi(diaChi);
        kh.setTrangThai(trangThai);
        kh.setTichDiem(Integer.parseInt(diemThuong));

        // Assuming you have a reference to your database class named "database"
        String result = khBUS.updateUser(kh);

             if (result.equals("Success")) {
            // Handle success
            System.out.println("Success: " + result);
            this.dispose();
            qlkh.reloadData();
            
            
        } else {
            // Handle failure
            System.out.println("Error: " + result);
            qlkh.reloadData();
        }
    } catch (Exception e) {
        // Handle exceptions
        e.printStackTrace();
    }
    }//GEN-LAST:event_button1ActionPerformed

    private void txtMAKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMAKHActionPerformed

    private void txtTENKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTENKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTENKHActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPointActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        try {
            String maKH = txtMAKH.getText();
            String tenKH = txtTENKH.getText();
            String sdtKH = txtSDT.getText();
            String diaChi = txtAddress.getText();
            String trangThai = txtStatus.getText();
            String diemThuong = txtPoint.getText();
            setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);


            // Debugging statements
            System.out.println("maKH: " + maKH);
            System.out.println("tenKH: " + tenKH);
            System.out.println("sdtKH: " + sdtKH);
            System.out.println("diaChi: " + diaChi);
            System.out.println("trangThai: " + trangThai);
            System.out.println("diemThuong: " + diemThuong);

            KhachHang kh = new KhachHang();
            kh.setMaKH(maKH);
            kh.setTen(tenKH);
            kh.setSDT(sdtKH);
            kh.setDiaChi(diaChi);
            kh.setTrangThai(trangThai);
            kh.setTichDiem(Integer.parseInt(diemThuong));

String result = khBUS.addKH_BanHang(kh);

        if (result.equals("Thêm khách hàng thành công")) {
            // Handle success
            System.out.println("Success: " + result);
            this.dispose();
            qlkh.reloadData();
            
        } else {
            // Handle failure
            System.out.println("Error: " + result);
            qlkh.reloadData();
        }
    } catch (Exception e) {
        // Handle exceptions
        e.printStackTrace();
    }
        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_button2ActionPerformed
    
    
    
    private QuanLyKhachHang qlkh;
    public ModifyUser(QuanLyKhachHang qlkh) {
        initComponents();
        String largestID = qlkh.getLargestIDFromTable();
        int nextID = Integer.parseInt(largestID) + 1; // Assuming largestID is an integer
        txtMAKH.setText(String.valueOf(nextID));
        txtMAKH.setEnabled(false);
        txtStatus.setText("1"); // Set default value for "Trạng Thái"
        txtPoint.setText("0");  // Set default value for "Điểm Thưởng"
        button1.setEnabled(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        this.qlkh = qlkh;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyUser().setVisible(true);
            }
        });
    }
    private KhachHang_BUS khBUS = new KhachHang_BUS();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.TextField txtAddress;
    private java.awt.TextField txtMAKH;
    private java.awt.TextField txtPoint;
    private java.awt.TextField txtSDT;
    private java.awt.TextField txtStatus;
    private java.awt.TextField txtTENKH;
    // End of variables declaration//GEN-END:variables

    
    static class setVisible {

        public setVisible() {
        }
    }

    
}
