/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.ChiTietLaptop_BUS;
import BUS.ChiTietPhieuNhap_BUS;
import BUS.Laptop_BUS;
import BUS.NhaCungCap_BUS;
import BUS.PhieuNhap_BUS;
import DTO.ChiTietLaptop;
import DTO.ChiTietPhieu;
import DTO.Laptop;
import DTO.NhanVien;
import DTO.PhieuNhap;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.SecureRandom;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.GroupLayout.Alignment;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JComboBox;
import javax.swing.event.AncestorListener;
import javax.swing.event.AncestorEvent;

/**
 *
 * @author ASUS
 */
public class NhapHang extends javax.swing.JFrame {
	Laptop_BUS laptop_BUS;
	PhieuNhap_BUS phieuNhap_BUS;
	ChiTietPhieuNhap_BUS chiTietPhieuNhap_BUS;
	ChiTietLaptop_BUS chiTietLaptop_BUS;
	NhaCungCap_BUS ncc_BUS;
	ArrayList<ChiTietPhieu> ctPhieuList;
	ArrayList<ChiTietLaptop> ctLaptopList;
	NhanVien NV;

    /**
     * Creates new form NhaCungCap
     */
    public NhapHang(NhanVien nv) {
    	this.NV = nv;
    	laptop_BUS = new Laptop_BUS();
    	phieuNhap_BUS = new PhieuNhap_BUS();
    	ncc_BUS = new NhaCungCap_BUS();
    	chiTietPhieuNhap_BUS = new ChiTietPhieuNhap_BUS();
    	chiTietLaptop_BUS = new ChiTietLaptop_BUS();
    	ctPhieuList = new ArrayList<>();
    	ctLaptopList = new ArrayList<>();
        initComponents();
    }
    public JFrame thisFr() {
		return this;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpThanhTieuDe = new javax.swing.JPanel();
        lblBanHang7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jpMenu = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblKhoHang = new javax.swing.JLabel();
        lblKhoHang.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new KhoHang(NV).setVisible(true);
                dispose();
        	}
        });
        lblNhapHang = new javax.swing.JLabel();
        lblBanHang = new javax.swing.JLabel();
        lblBanHang.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new BanHang(NV).setVisible(true);
                dispose();
        	}
        });
        lblBanHang1 = new javax.swing.JLabel();
        lblBanHang1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new QuanLyNhanVien(NV).setVisible(true);
                dispose();
        	}
        });
        lblBanHang2 = new javax.swing.JLabel();
        lblBanHang2.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new QuanLyKhachHang(NV).setVisible(true);
                dispose();
        	}
        });
        lblBanHang3 = new javax.swing.JLabel();
        lblBanHang3.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new QuanLyNhaCungCap(NV).setVisible(true);
                dispose();
        	}
        });
        lblBanHang4 = new javax.swing.JLabel();
        lblBanHang4.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new PhieuNhapHang(NV).setVisible(true);
                dispose();
        	}
        });
        lblBanHang5 = new javax.swing.JLabel();
        lblBanHang5.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new HoaDonBanHang(NV).setVisible(true);
                dispose();
        	}
        });
        lblBanHang6 = new javax.swing.JLabel();
        lblBanHang6.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new ThongKe(NV).setVisible(true);
                dispose();
        	}
        });


        jpKho = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		jTextField1.setText("");
        	}
        });
        lbTimKiem = new javax.swing.JLabel();
        lbTimKiem.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		Search_String(jTable1, jTextField1.getText().toString()); // tìm kiếm 
        	}
        });
        jpPhieuNhap = new javax.swing.JTabbedPane();
        jpThongTinSanPham = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        
        jTable1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		
        		
        	}
        });
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTable2.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		int row = jTable2.getSelectedRow();
        		
        		callTableCTLaptops(row);
        		
        	}
        });
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		addPhieuNhap();
        	}
        });
        jpChiTietHoaDon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblMaPhieu = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblNgayNhap = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTongHoaDon = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTable3.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		int row = jTable3.getSelectedRow();
        		
        		callTableCTLaptops(row);
        	}
        });
        lblBanHang7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/user.png"))); // NOI18N
        lblBanHang7.setText("Tài khoản");
        lblBanHang7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHang7MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(1500, 740));

        jpThanhTieuDe.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỆ THỐNG QUẢN LÝ CỬA HÀNG LAPTOP");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/LOGO.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Profile.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Logout.png"))); // NOI18N

        javax.swing.GroupLayout jpThanhTieuDeLayout = new javax.swing.GroupLayout(jpThanhTieuDe);
        jpThanhTieuDe.setLayout(jpThanhTieuDeLayout);
        jpThanhTieuDeLayout.setHorizontalGroup(
            jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThanhTieuDeLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1016, 1016, 1016)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpThanhTieuDeLayout.setVerticalGroup(
            jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThanhTieuDeLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpThanhTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Avatar.png"))); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText(NV.getTenNV());

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblChucVu.setText("Quản lý");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Line.png"))); // NOI18N

        lblKhoHang.setBackground(new java.awt.Color(255, 255, 255));
        lblKhoHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KhoHang.png"))); // NOI18N
        lblKhoHang.setText("Kho hàng");

        lblNhapHang.setBackground(new java.awt.Color(102, 204, 255));
        lblNhapHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhapHang.png"))); // NOI18N
        lblNhapHang.setText("Nhập hàng");
        lblNhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhapHang.setOpaque(true);

        lblBanHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/BanHang.png"))); // NOI18N
        lblBanHang.setText("Bán hàng");

        lblBanHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhanVien.png"))); // NOI18N
        lblBanHang1.setText("Nhân viên");

        lblBanHang2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KhachHang.png"))); // NOI18N
        lblBanHang2.setText("Khách hàng");

        lblBanHang3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhaCungCap.png"))); // NOI18N
        lblBanHang3.setText("Nhà cung cấp");

        lblBanHang4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PhieuNhapHang_1.png"))); // NOI18N
        lblBanHang4.setText("Phiếu nhập hàng");

        lblBanHang5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Bill.png"))); // NOI18N
        lblBanHang5.setText("Hóa đơn bán hàng");

        lblBanHang6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Thống kê.png"))); // NOI18N
        lblBanHang6.setText("Thống kê doanh thu");

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBanHang2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKhoHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblChucVu)
                .addGap(76, 76, 76))
            .addGroup(jpMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblBanHang7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblAvatar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKhoHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNhapHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang7)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        jpKho.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextField1.setText("Nhập thông tin tìm kiếm");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        lbTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/TimKiem.png")));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Bảng kho laptop");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Bảng nhập laptop");

        ArrayList<Laptop> listLaptops = laptop_BUS.getAllLaptop();
        
        Object[][] data_laptops = new Object[listLaptops.size()][];
		for (int i=0;i<listLaptops.size();i++) {
			Laptop obj = listLaptops.get(i);
			data_laptops[i]= new Object[]{obj.getID(),obj.getTen(),obj.getSoLuongTonKho(),obj.getGia(),
					obj.getTrangThai().equals("1")?"Tồn tại":"Không Tồn tại"};
		}
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        	data_laptops,
            new String [] {
                "ID", "Tên", "Tồn Kho", "Giá", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
            		"ID", "Tên",  "Giá", "Số lượng Nhập"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("TỔNG TIỀN:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("0");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("CONFIRM");

        javax.swing.GroupLayout jpThongTinSanPhamLayout = new javax.swing.GroupLayout(jpThongTinSanPham);
        jpThongTinSanPhamLayout.setHorizontalGroup(
        	jpThongTinSanPhamLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 625, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 625, GroupLayout.PREFERRED_SIZE))
        		.addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
        			.addGap(257)
        			.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 509, Short.MAX_VALUE)
        			.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
        			.addGap(248))
        		.addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
        			.addContainerGap(714, Short.MAX_VALUE)
        			.addComponent(jLabel8)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
        			.addGap(109)
        			.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        			.addGap(52))
        );
        jpThongTinSanPhamLayout.setVerticalGroup(
        	jpThongTinSanPhamLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jpThongTinSanPhamLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jpThongTinSanPhamLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(jpThongTinSanPhamLayout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jpThongTinSanPhamLayout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        							.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)))
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 449, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        jpThongTinSanPham.setLayout(jpThongTinSanPhamLayout);

        jpPhieuNhap.addTab("Thông tin sản phẩm ", jpThongTinSanPham);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Chi tiết phiếu nhập");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Mã phiếu nhập :");

        lblMaPhieu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMaPhieu.setText(phieuNhap_BUS.getNewCode());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Ngày lập :");

        lblNgayNhap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Timer timer = new Timer();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                Calendar calendar = Calendar.getInstance();
                lblNgayNhap.setText(dateFormat.format(calendar.getTime()));
            }
        }, 0, 1000); // Cập nhật mỗi giây (1000 milliseconds)

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Mã nhân viên :");

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMaNV.setText(NV.getMaNV());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Tên nhân viên :");

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTenNV.setText(NV.getTenNV());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Tổng tiền :");

        lblTongHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTongHoaDon.setText("0");

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
            	"ID", "Tên",  "Giá", "Số lượng Nhập"
            }
        ));
        jScrollPane4.setViewportView(jTable3);
        
        lblNhCungCp = new JLabel();
        lblNhCungCp.setText("Nhà cung cấp:");
        lblNhCungCp.setFont(new Font("Segoe UI", Font.BOLD, 16));
        
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Xoa.png"))); // NOI18N
        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Them.png"))); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Sửa.png"))); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        ArrayList<String> nameNCC = new ArrayList<>();
        for (DTO.NhaCungCap na: ncc_BUS.getAllNhaCungCap()) {
        	nameNCC.add(na.getTenNCC());
        }
        comboBox = new JComboBox<String>(new DefaultComboBoxModel<>(nameNCC.toArray(new String[0])));

        
        javax.swing.GroupLayout jpChiTietHoaDonLayout = new javax.swing.GroupLayout(jpChiTietHoaDon);
        jpChiTietHoaDonLayout.setHorizontalGroup(
        	jpChiTietHoaDonLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        			.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        					.addGap(52)
        					.addComponent(btnQuayLai, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
        					.addComponent(btnThanhToan, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        					.addGap(40))
        				.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        					.addGap(17)
        					.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        							.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        								.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.LEADING, false)
        									.addComponent(jLabel12, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        								.addComponent(lblNhCungCp, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE))
        							.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        									.addGap(19)
        									.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(lblNgayNhap, GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        										.addComponent(lblMaNV, GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        										.addComponent(lblTenNV, GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        										.addComponent(lblMaPhieu, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)))
        								.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        									.addGap(18)
        									.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE))))
        						.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        							.addComponent(jLabel15)
        							.addGap(41)
        							.addComponent(lblTongHoaDon, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, 45, Short.MAX_VALUE)))))
        			.addGap(30)
        			.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 759, GroupLayout.PREFERRED_SIZE)
        			.addGap(16))
        		.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        			.addGap(545)
        			.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(485, Short.MAX_VALUE))
        );
        jpChiTietHoaDonLayout.setVerticalGroup(
        	jpChiTietHoaDonLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        			.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        					.addGap(35)
        					.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        					.addGap(46)
        					.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
        					.addGap(126)
        					.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel11)
        						.addComponent(lblMaPhieu))
        					.addGap(29)
        					.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel12)
        						.addComponent(lblNgayNhap))
        					.addGap(30)
        					.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel13)
        						.addComponent(lblMaNV))
        					.addGap(32)
        					.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel14)
        						.addComponent(lblTenNV))
        					.addGap(30)
        					.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblNhCungCp, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        						.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
        					.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel15)
        						.addComponent(lblTongHoaDon))
        					.addGap(69)
        					.addGroup(jpChiTietHoaDonLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(btnThanhToan, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnQuayLai, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpChiTietHoaDon.setLayout(jpChiTietHoaDonLayout);

        jpPhieuNhap.addTab("Phiếu nhập", jpChiTietHoaDon);

        javax.swing.GroupLayout jpKhoLayout = new javax.swing.GroupLayout(jpKho);
        jpKhoLayout.setHorizontalGroup(
        	jpKhoLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpKhoLayout.createSequentialGroup()
        			.addGap(14)
        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 332, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lbTimKiem)
        			.addContainerGap(921, Short.MAX_VALUE))
        		.addGroup(jpKhoLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jpPhieuNhap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jpKhoLayout.setVerticalGroup(
        	jpKhoLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpKhoLayout.createSequentialGroup()
        			.addGap(22)
        			.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(lbTimKiem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jpPhieuNhap, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jpKho.setLayout(jpKhoLayout);
        
        jpKhoLayout.setHorizontalGroup(
                jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpKhoLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbTimKiem)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton3)
                    .addGap(183, 183, 183))
                .addGroup(jpKhoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpPhieuNhap)
                    .addContainerGap())
            );
            jpKhoLayout.setVerticalGroup(
                jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpKhoLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1)
                        .addGroup(jpKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(18, 18, 18)
                    .addComponent(jpPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap())
            );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpThanhTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpThanhTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void addPhieuNhap() {
    	if (ctPhieuList.size() == 0) {
    		JOptionPane.showMessageDialog(null, "Không có máy nhập!");
    		return;
    	}
		int MaPhieu = Integer.parseInt(lblMaPhieu.getText().toString());
		Date currentDateTime = new Date();
        int TongTien = Integer.parseInt(jLabel9.getText().toString());
        String nhaCungCap = "";
        for (DTO.NhaCungCap tCap : ncc_BUS.getAllNhaCungCap()) {
        	if (comboBox.getSelectedItem().toString().equals(tCap.getTenNCC()))
        		nhaCungCap = tCap.getMaNCC();
        }
        PhieuNhap nhap = new PhieuNhap(MaPhieu, currentDateTime, TongTien, nhaCungCap, NV.getMaNV());
        
        
        for (DTO.ChiTietLaptop ctp : chiTietLaptop_BUS.getListChiTietLaptop()) {
        	for (DTO.ChiTietLaptop ctd: ctLaptopList) {
        		if (ctd.getIDRieng().equals(ctp.getIDRieng())) {
        			JOptionPane.showMessageDialog(null, "ID riêng " + ctd.getIDRieng() + " đã tồn tại!");
                	return;
        		}
        	}
        }
        
        
        if (phieuNhap_BUS.addPhieuNhap(nhap).equals("Thêm phiếu nhập thất bại")) {
        	JOptionPane.showMessageDialog(null, "Tạo Không thành công!");
        	return;
        }
        
        for (DTO.ChiTietPhieu ctp : ctPhieuList) {
        	if (chiTietPhieuNhap_BUS.addChiTietPhieuNhap(ctp).equals("Xảy ra lỗi")) {
            	JOptionPane.showMessageDialog(null, "Tạo Không thành công!");
            	return;
            }
        	for (DTO.Laptop t : laptop_BUS.getAllLaptop()) {
        		if (ctp.getID().equals(t.getID())) {
        			t.setSoLuongTonKho(t.getSoLuongTonKho() + ctp.getSoLuong());
        			t.setGia(ctp.getGia());
        			laptop_BUS.TruSoLuongTonKho(t.getSoLuongTonKho(), t.getID());
        			laptop_BUS.editLaptop(t);
        		}
            }
        }
        
        for (DTO.ChiTietLaptop ctp : ctLaptopList) {
        	if(!chiTietLaptop_BUS.addChiTietLaptop(ctp)) {
        		JOptionPane.showMessageDialog(null, "Tạo Không thành công!");
            	return;
        	}
        }
        ctPhieuList = new ArrayList<>();
        ctLaptopList = new ArrayList<>();
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    
                },
                new String [] {
                		"ID", "Tên",  "Giá", "Số lượng Nhập"
                }
            ));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                	"ID", "Tên",  "Giá", "Số lượng Nhập"
                }
            ));
        
		int sumMoney = 0;
		
		jLabel9.setText(sumMoney + "");
		lblTongHoaDon.setText(jLabel9.getText());
		
		lblMaPhieu.setText((MaPhieu + 1) + "");
        
        JOptionPane.showMessageDialog(null, "Tạo thành công!");
	}
	protected void callTableCTLaptops(int row) {
    	JPanel panel_1 = new JPanel();
		panel_1.setBounds(0, 0, 341, 259);
		panel_1.setLayout(new BorderLayout(0, 0));
		
		JPanel panel_2 = new JPanel();
		panel_1.add(panel_2, BorderLayout.NORTH);
		
		JScrollPane scrollPane = new JScrollPane();
		panel_1.add(scrollPane, BorderLayout.CENTER);
		
		JTable table = new JTable();
		table.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	            },
	            new String [] {
	            	"STT", "Serial"
	            }
	        ));
		scrollPane.setViewportView(table);
		DefaultTableModel model = (DefaultTableModel) table.getModel();
		int i = 1;
		for (ChiTietLaptop t : ctLaptopList) {
			if (t.getMauLapTop().equals(jTable2.getValueAt(row, 0)))
				model.addRow(new Object[] {i++, t.getIDRieng()});
			
		}
		
		JDialog dialog = new JDialog(thisFr(), "Nhập mã máy", true);
		dialog.setSize(300,300);
		dialog.setLocationRelativeTo(jTable2);
		dialog.getContentPane().add(panel_1);
		
		dialog.setVisible(true);
		
	}
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public TableRowSorter Search_table(JTable table) {	
		DefaultTableModel model = (DefaultTableModel) table.getModel();
		TableRowSorter sorter = new TableRowSorter<>(model);
		table.setRowSorter(sorter);
		sorter.setRowFilter(null);
		return sorter;
	}
	@SuppressWarnings("unchecked")
	public void Search_String(JTable table,String name) {		
		RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter("(?i)" + name);
		this.Search_table(table).setRowFilter(name == "" ? null : filter);
	}
	private void lblBanHang7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHang7MouseClicked
        // TODO add your handling code here:
        new QuanLyTaiKhoan(NV).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHang7MouseClicked
	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
		Search_String(jTable1, jTextField1.getText().toString()); // tìm kiếm 
    }//GEN-LAST:event_jTextField1ActionPerformed
	
	public String generateRandomString(int length) {
        StringBuilder randomString = new StringBuilder(length);
        SecureRandom secureRandom = new SecureRandom();
        do {
	        for (int i = 0; i < length; i++) {
	            int randomCharIndex = secureRandom.nextInt(ALLOWED_CHARACTERS.length());
	            char randomChar = ALLOWED_CHARACTERS.charAt(randomCharIndex);
	            randomString.append(randomChar);
	        }
        } while(isStringInList(randomString.toString(), chiTietLaptop_BUS.getListChiTietLaptop()));

        return randomString.toString();
    }

    public boolean isStringInList(String str, ArrayList<ChiTietLaptop> stringList) {
        for (ChiTietLaptop s : stringList) {
            if (s.getIDRieng().equals(str)) {
                return true;
            }
        }
        return false;
    }
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = jTable2.getSelectedRow();
        if (row == -1) {
			JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng trong bảng nhập hàng");
			return;
		}
        
        for (ChiTietPhieu t: ctPhieuList) {
        	if (t.getID().equals(jTable2.getValueAt(row, 0))) {
        		ctPhieuList.remove(t);
        		break;
        	}
        }
        for (int i = 0; i < ctLaptopList.size();i++) {
        	ChiTietLaptop t = ctLaptopList.get(i);
        	if (t.getMauLapTop().equals(jTable2.getValueAt(row, 0))) {
        		ctLaptopList.remove(i);
        	}
        	i--;
        }
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
		model.removeRow(row);

        DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
		model1.removeRow(row);
		
		int sumMoney = 0;
		for (ChiTietPhieu t: ctPhieuList )
			sumMoney += t.getGia() * t.getSoLuong();
		
		jLabel9.setText(sumMoney + "");
		lblTongHoaDon.setText(jLabel9.getText());
        
    }//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		int row = jTable1.getSelectedRow();
		if (row == -1) {
			JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng trong bảng Laptop");
			return;
		}
		
		if (ctPhieuList.size() > 0) {
			for (ChiTietPhieu t : ctPhieuList) {
				if (t.getID().equals(jTable1.getValueAt(row, 0))) {
					JOptionPane.showMessageDialog(null, "Sản phẩm đã thêm trước đó!");
					return;
				}
			}
		}
		if (jTable1.getValueAt(row, 4).toString().equals("Không Tồn tại")) {
			JOptionPane.showMessageDialog(null, "Không thêm được vì không tồn tại!");
			return;
		} 
		
		JPanel panel = new JPanel();
		panel.setBounds(0, 0, 434, 261);
		panel.setLayout(null);
		
		JLabel lblNewLabel = new JLabel("Giá Nhập:");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 14));
		lblNewLabel.setBounds(10, 11, 85, 23);
		panel.add(lblNewLabel);
		
		JTextField textField = new JTextField();
		textField.setFont(new Font("Tahoma", Font.PLAIN, 14));
		textField.setBounds(99, 11, 168, 23);
		panel.add(textField);
		textField.setColumns(10);
		
		JLabel lblSLng = new JLabel("Số lượng:");
		lblSLng.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 14));
		lblSLng.setBounds(10, 45, 85, 23);
		panel.add(lblSLng);
		
		JTextField textField_1 = new JTextField();
		textField_1.setFont(new Font("Tahoma", Font.PLAIN, 14));
		textField_1.setColumns(10);
		textField_1.setBounds(99, 45, 168, 23);
		panel.add(textField_1);
		
		JDialog dialog = new JDialog(thisFr(), "Bổ Sung", true);
		dialog.setSize(300, 160);
		dialog.setLocationRelativeTo(jLabel6);
		
		JButton btnNewButton = new JButton("Done");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (textField.getText().toString().isEmpty() || textField_1.getText().toString().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin!");
					return;
				}
				
				DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
				model.addRow(new Object[] {jTable1.getValueAt(row, 0),
						jTable1.getValueAt(row, 1), textField.getText().toString(), textField_1.getText().toString()});
				model = (DefaultTableModel) jTable3.getModel();
				model.addRow(new Object[] {jTable1.getValueAt(row, 0),
						jTable1.getValueAt(row, 1), textField.getText().toString(), textField_1.getText().toString()});
				ctPhieuList.add(new ChiTietPhieu(jTable1.getValueAt(row, 0).toString(), 
						Integer.parseInt(textField.getText().toString()), Integer.parseInt(lblMaPhieu.getText().toString()), Integer.parseInt(textField_1.getText().toString())));
				int sumMoney = 0;
				for (ChiTietPhieu t: ctPhieuList )
					sumMoney += t.getGia() * t.getSoLuong();
				
				int sol = Integer.parseInt(textField_1.getText().toString());
				Calendar calendar = Calendar.getInstance();
		        Date currentDate = calendar.getTime();
				for (int i = 0;i < sol;i++) {
					ChiTietLaptop tietLaptop = new ChiTietLaptop(generateRandomString(9)
							,"1", jTable1.getValueAt(row, 0).toString(), currentDate );
					ctLaptopList.add(tietLaptop);
				}
				
				jLabel9.setText(sumMoney + "");
				lblTongHoaDon.setText(jLabel9.getText());
				dialog.dispose();
			}
		});
		btnNewButton.setBounds(33, 79, 89, 23);
		panel.add(btnNewButton);
		
		JButton btnNewButton_1 = new JButton("Cancel");
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dialog.dispose();
			}
		});
		btnNewButton_1.setBounds(159, 79, 89, 23);
		panel.add(btnNewButton_1);

		dialog.getContentPane().add(panel);
		dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		int row = jTable2.getSelectedRow();
		if (row == -1) {
			JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng trong bảng nhập hàng");
			return;
		}
		
		JPanel panel = new JPanel();
		panel.setBounds(0, 0, 434, 261);
		panel.setLayout(null);
		
		JLabel lblNewLabel = new JLabel("Giá Nhập:");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 14));
		lblNewLabel.setBounds(10, 11, 85, 23);
		panel.add(lblNewLabel);
		
		JTextField textField = new JTextField();
		textField.setFont(new Font("Tahoma", Font.PLAIN, 14));
		textField.setBounds(99, 11, 168, 23);
		panel.add(textField);
		textField.setText(jTable2.getValueAt(row, 2).toString());
		textField.setColumns(10);
		
		JLabel lblSLng = new JLabel("Số lượng:");
		lblSLng.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 14));
		lblSLng.setBounds(10, 45, 85, 23);
		panel.add(lblSLng);
		
		JTextField textField_1 = new JTextField();
		textField_1.setFont(new Font("Tahoma", Font.PLAIN, 14));
		textField_1.setColumns(10);
		textField_1.setBounds(99, 45, 168, 23);
		textField_1.setText(jTable2.getValueAt(row, 3).toString());
		panel.add(textField_1);
		
		JDialog dialog = new JDialog(thisFr(), "Bổ Sung", true);
		dialog.setSize(300, 160);
		dialog.setLocationRelativeTo(jLabel6);
		
		JButton btnNewButton = new JButton("Done");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (textField.getText().toString().isEmpty() || textField_1.getText().toString().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin!");
					return;
				}
				for (ChiTietPhieu t: ctPhieuList) {
		        	if (t.getID().equals(jTable2.getValueAt(row, 0))) {
		        		ctPhieuList.remove(t);
		        		break;
		        	}
		        }
		        for (int i = 0; i < ctLaptopList.size();i++) {
		        	ChiTietLaptop t = ctLaptopList.get(i);
		        	if (t.getMauLapTop().equals(jTable2.getValueAt(row, 0))) {
		        		ctLaptopList.remove(i);
		        	}
		        	i--;
		        }
		        DefaultTableModel model3 = (DefaultTableModel) jTable2.getModel();
				model3.removeRow(row);

		        DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
				model1.removeRow(row);
				
				DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
				model.addRow(new Object[] {jTable1.getValueAt(row, 0),
						jTable1.getValueAt(row, 1), textField.getText().toString(), textField_1.getText().toString()});
				model = (DefaultTableModel) jTable3.getModel();
				model.addRow(new Object[] {jTable1.getValueAt(row, 0),
						jTable1.getValueAt(row, 1), textField.getText().toString(), textField_1.getText().toString()});
				ctPhieuList.add(new ChiTietPhieu(jTable1.getValueAt(row, 0).toString(), 
						Integer.parseInt(textField.getText().toString()), Integer.parseInt(lblMaPhieu.getText().toString()), Integer.parseInt(textField_1.getText().toString())));
				int sumMoney = 0;
				for (ChiTietPhieu t: ctPhieuList )
					sumMoney += t.getGia() * t.getSoLuong();
				
				int sol = Integer.parseInt(textField_1.getText().toString());
				Calendar calendar = Calendar.getInstance();
		        Date currentDate = calendar.getTime();
				for (int i = 0;i < sol;i++) {
					ChiTietLaptop tietLaptop = new ChiTietLaptop(generateRandomString(9)
							,"1", jTable1.getValueAt(row, 0).toString(), currentDate );
					ctLaptopList.add(tietLaptop);
				}
				
				jLabel9.setText(sumMoney + "");
				lblTongHoaDon.setText(jLabel9.getText());
				dialog.dispose();
			}
		});
		btnNewButton.setBounds(33, 79, 89, 23);
		panel.add(btnNewButton);
		
		JButton btnNewButton_1 = new JButton("Cancel");
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dialog.dispose();
			}
		});
		btnNewButton_1.setBounds(159, 79, 89, 23);
		panel.add(btnNewButton_1);

		dialog.getContentPane().add(panel);
		dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
//        jpPhieuNhap.setSelectedIndex(0);
//        txtFind.setEnabled(true);
//        btnAdd.setEnabled(true);
//        btnDelete.setEnabled(true);
//        btnEdit.setEnabled(true);
//        cbxNXB.setEnabled(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
    	addPhieuNhap();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        NhanVien duy = new NhanVien("NV001", "Trần Khánh Duy", "0001", "LA",  "26/10", "001", 
        		"trankhanhduy12a12@gmail.com", "1", true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapHang(duy).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpChiTietHoaDon;
    private javax.swing.JPanel jpKho;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JTabbedPane jpPhieuNhap;
    private javax.swing.JPanel jpThanhTieuDe;
    private javax.swing.JPanel jpThongTinSanPham;
    private javax.swing.JLabel lbTimKiem;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblBanHang1;
    private javax.swing.JLabel lblBanHang2;
    private javax.swing.JLabel lblBanHang3;
    private javax.swing.JLabel lblBanHang4;
    private javax.swing.JLabel lblBanHang5;
    private javax.swing.JLabel lblBanHang6;
    private javax.swing.JLabel lblBanHang7;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblKhoHang;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaPhieu;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNgayNhap;
    private javax.swing.JLabel lblNhapHang;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTongHoaDon;
    private JLabel lblNhCungCp;
    private JComboBox<String> comboBox;
    private final String ALLOWED_CHARACTERS = "0123456789";
}
