/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import BUS.NhanVien_BUS;
import BUS.TaiKhoan_BUS;
import DTO.NhanVien;
import DTO.TaiKhoan;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JTextField;
import javax.swing.JComboBox;

/**
 *
 * @author ASUS
 */
public class QuanLyTaiKhoan extends javax.swing.JFrame {
    
    public static NhanVien NV;

    /**
     * Creates new form NhaCungCap
     */
    public QuanLyTaiKhoan(NhanVien NV) {
        initComponents();
        this.NV = NV;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpThanhTieuDe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpMenu = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblKhoHang = new javax.swing.JLabel();
        lblNhapHang = new javax.swing.JLabel();
        lblBanHang = new javax.swing.JLabel();
        lblBanHang1 = new javax.swing.JLabel();
        lblBanHang2 = new javax.swing.JLabel();
        lblBanHang3 = new javax.swing.JLabel();
        lblBanHang4 = new javax.swing.JLabel();
        lblBanHang5 = new javax.swing.JLabel();
        lblBanHang6 = new javax.swing.JLabel();
        jpKho = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        lbTimKiem = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(1500, 740));

        jpThanhTieuDe.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỆ THỐNG QUẢN LÝ CỬA HÀNG LAPTOP");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/LOGO.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Profile.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Logout.png"))); // NOI18N

        javax.swing.GroupLayout jpThanhTieuDeLayout = new javax.swing.GroupLayout(jpThanhTieuDe);
        jpThanhTieuDe.setLayout(jpThanhTieuDeLayout);
        jpThanhTieuDeLayout.setHorizontalGroup(
            jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThanhTieuDeLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(12, 12, 12))
        );
        jpThanhTieuDeLayout.setVerticalGroup(
            jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThanhTieuDeLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpThanhTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThanhTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Avatar.png"))); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Lê Hoài Nam");

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblChucVu.setText("Quản lý");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Line.png"))); // NOI18N

        lblKhoHang.setBackground(new java.awt.Color(102, 204, 255));
        lblKhoHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KhoHang.png"))); // NOI18N
        lblKhoHang.setText("Kho hàng");
        lblKhoHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKhoHang.setOpaque(true);

        lblNhapHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhapHang.png"))); // NOI18N
        lblNhapHang.setText("Nhập hàng");

        lblBanHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/BanHang.png"))); // NOI18N
        lblBanHang.setText("Bán hàng");

        lblBanHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhanVien.png"))); // NOI18N
        lblBanHang1.setText("Nhân viên");

        lblBanHang2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/KhachHang.png"))); // NOI18N
        lblBanHang2.setText("Khách hàng");

        lblBanHang3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NhaCungCap.png"))); // NOI18N
        lblBanHang3.setText("Nhà cung cấp");

        lblBanHang4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PhieuNhapHang_1.png"))); // NOI18N
        lblBanHang4.setText("Phiếu nhập hàng");

        lblBanHang5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Bill.png"))); // NOI18N
        lblBanHang5.setText("Hóa đơn bán hàng");

        lblBanHang6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBanHang6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Thống kê.png"))); // NOI18N
        lblBanHang6.setText("Thống kê doanh thu");

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBanHang2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKhoHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBanHang6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblChucVu)
                .addGap(76, 76, 76))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblAvatar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKhoHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNhapHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang6)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        jpKho.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextField1.setText("Nhập thông tin tìm kiếm");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        
        jTextField1.addKeyListener(new java.awt.event.KeyListener(){

			@Override
			public void keyTyped(KeyEvent e) {
				// TODO Auto-generated method stu
			}

			@Override
			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void keyReleased(KeyEvent evt) {
				// TODO Auto-generated method stub
				jTextField1KeyListener(evt);
			}
        	
        });

        lbTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/TimKiem.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Xoa.png"))); // NOI18N
        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Them.png"))); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Sửa.png"))); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            update(),
            new String [] {
                "Tên đăng nhập","Mật khẩu","Phân quyền"
            }
        ));
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                if (row >= 0 ) {
                    List<TaiKhoan> list = new TaiKhoan_BUS().getListTaiKhoan2();
                	String tenDN = list.get(row).getTenDN();
                	String matkhau = list.get(row).getMatKhau();
                	String phanquyen = list.get(row).getPhanQuyen();
                	
                	textField.setText(tenDN);
                	textField_1.setText(matkhau);

                	if( phanquyen.equals("Quanly") )
                		comboBox.setSelectedIndex(0);
                	else
                		comboBox.setSelectedIndex(1);
                }
            }
        });
        
        
        
        jScrollPane1.setViewportView(jTable1);
        
        JLabel lblNewLabel = new JLabel("Tên đăng nhập:");
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 20));
        
        JLabel lblNewLabel_1 = new JLabel("Mật khẩu:");
        lblNewLabel_1.setFont(new Font("Tahoma", Font.BOLD, 20));
        
        JLabel lblNewLabel_2 = new JLabel("Phân quyền:");
        lblNewLabel_2.setFont(new Font("Tahoma", Font.BOLD, 20));
        
        textField = new JTextField();
        textField.setEnabled(false);
        textField.setFont(new Font("Tahoma", Font.PLAIN, 20));
        textField.setColumns(10);
        
        textField_1 = new JTextField();
        textField_1.setFont(new Font("Tahoma", Font.PLAIN, 20));
        textField_1.setColumns(10);
        
        String p[] = {"Quản lý","Nhân viên"};
        comboBox = new JComboBox(p);
        comboBox.setFont(new Font("Tahoma", Font.PLAIN, 20));
        
        String search[] = {"Tên đăng nhập","Phân quyền"};
        comboBox_1 = new JComboBox(search);
        comboBox_1.setFont(new Font("Tahoma", Font.BOLD, 16));
        
        lblNewLabel_3 = new JLabel("Chọn tài khoản:");
        lblNewLabel_3.setFont(new Font("Tahoma", Font.BOLD, 20));
        
        lblNewLabel_4 = new JLabel("Mật khẩu:");
        lblNewLabel_4.setFont(new Font("Tahoma", Font.BOLD, 20));
        
        lblNewLabel_5 = new JLabel("Chọn quyền:");
        lblNewLabel_5.setFont(new Font("Tahoma", Font.BOLD, 20));
        
        String[] list_addTK = new NhanVien_BUS().getListNhanVien_maNV_noTK();
        model = new DefaultComboBoxModel<>(list_addTK);
        comboBox_2 = new JComboBox<>(model);
        comboBox_2.setFont(new Font("Tahoma", Font.PLAIN, 20));
        
        textField_2 = new JTextField();
        textField_2.setFont(new Font("Tahoma", Font.PLAIN, 20));
        textField_2.setColumns(10);
        
        comboBox_3 = new JComboBox(p);
        comboBox_3.setFont(new Font("Tahoma", Font.PLAIN, 20));

        javax.swing.GroupLayout jpKhoLayout = new javax.swing.GroupLayout(jpKho);
        jpKhoLayout.setHorizontalGroup(
        	jpKhoLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jpKhoLayout.createSequentialGroup()
        			.addGap(52)
        			.addGroup(jpKhoLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jpKhoLayout.createSequentialGroup()
        					.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jpKhoLayout.createSequentialGroup()
        							.addComponent(lblNewLabel_5)
        							.addPreferredGap(ComponentPlacement.RELATED))
        						.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        							.addGroup(jpKhoLayout.createParallelGroup(Alignment.TRAILING, false)
        								.addComponent(lblNewLabel_2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblNewLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblNewLabel_1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
        								.addComponent(lblNewLabel_3, Alignment.LEADING))
        							.addGroup(jpKhoLayout.createSequentialGroup()
        								.addGap(68)
        								.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE))
        							.addGroup(jpKhoLayout.createSequentialGroup()
        								.addComponent(lblNewLabel_4, GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        								.addPreferredGap(ComponentPlacement.RELATED))))
        					.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jpKhoLayout.createSequentialGroup()
        							.addGap(7)
        							.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING, false)
        									.addComponent(textField)
        									.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 239, GroupLayout.PREFERRED_SIZE))
        								.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(jpKhoLayout.createSequentialGroup()
        							.addGap(95)
        							.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jpKhoLayout.createSequentialGroup()
        							.addGap(18)
        							.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(comboBox_3, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        								.addGroup(jpKhoLayout.createSequentialGroup()
        									.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        										.addComponent(comboBox_2, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE))
        									.addGap(49)
        									.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)))))
        					.addGap(50)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 649, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(jpKhoLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 580, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 332, GroupLayout.PREFERRED_SIZE)
        					.addGap(30)
        					.addComponent(lbTimKiem)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(comboBox_1, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE)
        					.addGap(72)))
        			.addGap(52))
        );
        jpKhoLayout.setVerticalGroup(
        	jpKhoLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpKhoLayout.createSequentialGroup()
        			.addGap(42)
        			.addGroup(jpKhoLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        					.addGroup(jpKhoLayout.createSequentialGroup()
        						.addGap(16)
        						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addComponent(lbTimKiem, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
        				.addComponent(comboBox_1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE))
        			.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jpKhoLayout.createSequentialGroup()
        					.addGap(19)
        					.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(comboBox_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblNewLabel_3))
        					.addGap(24)
        					.addGroup(jpKhoLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblNewLabel_4)
        						.addComponent(jButton2))
        					.addGap(20)
        					.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(comboBox_3, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblNewLabel_5))
        					.addGap(82)
        					.addGroup(jpKhoLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textField, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        					.addGap(27)
        					.addGroup(jpKhoLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblNewLabel_1)
        						.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        					.addGap(65)
        					.addGroup(jpKhoLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblNewLabel_2)
        						.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        					.addGap(48)
        					.addGroup(jpKhoLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jButton1)
        						.addComponent(jButton3, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        					.addGap(113))
        				.addGroup(jpKhoLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 545, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        );
        jpKho.setLayout(jpKhoLayout);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpThanhTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpThanhTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    	String tenDN = String.valueOf(comboBox_2.getItemAt(comboBox.getSelectedIndex()));
    	String mk = textField_2.getText();
    	String pq = String.valueOf(comboBox_3.getItemAt(comboBox.getSelectedIndex()));
    	String phanquyen;
    	if( pq.equals("Quản lý"))
    		phanquyen = "Quanly";
    	else
    		phanquyen = "Nhanvien";
    	if( !mk.equals("") && !tenDN.equals("")) {
    		TaiKhoan tk = new TaiKhoan(tenDN,mk,phanquyen);
			JOptionPane.showMessageDialog(jPanel2, new TaiKhoan_BUS().themTK(tk));
			jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            update(),
	            new String [] {
	            		"Tên đăng nhập","Mật khẩu","Phân quyền"
	            }
	        ));
			model.removeElement(tenDN);
    	}
    	else if(tenDN.equals(""))
    		JOptionPane.showMessageDialog(jPanel2, "Chọn 1 tài khoản để thêm !","Error",0);
    	else 
    		JOptionPane.showMessageDialog(jPanel2, "Không được để trống mật khẩu !","Error",0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    	String tenDN = textField.getText();
    	String mk = textField_1.getText();
    	String pq = String.valueOf(comboBox.getItemAt(comboBox.getSelectedIndex()));
    	String phanquyen;
    	if( pq.equals("Quản lý"))
    		phanquyen = "Quanly";
    	else
    		phanquyen = "Nhanvien";
    	if( !tenDN.equals("") ) {
    		TaiKhoan tk = new TaiKhoan(tenDN,mk,phanquyen);
			JOptionPane.showMessageDialog(jPanel2, new TaiKhoan_BUS().suaTK(tk));
			jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            update(),
	            new String [] {
	            		"Tên đăng nhập","Mật khẩu","Phân quyền"
	            }
	        ));
    	}
    	else
    		JOptionPane.showMessageDialog(jPanel2, "Chọn một tài khoản để sửa !","Error",0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	String tenDN = textField.getText();
    	String mk = textField_1.getText();
    	String pq = String.valueOf(comboBox.getItemAt(comboBox.getSelectedIndex()));
    	String phanquyen;
    	if( pq.equals("Quản lý"))
    		phanquyen = "Quanly";
    	else
    		phanquyen = "Nhanvien";
    	if( !tenDN.equals("") ) {
    		TaiKhoan tk = new TaiKhoan(tenDN,mk,phanquyen);
    		int choose = JOptionPane.showConfirmDialog(jPanel2, "Bạn có chắc muốn xóa tài khoản "+tenDN+" ?");
    		if( choose == JOptionPane.YES_OPTION ) {
				JOptionPane.showMessageDialog(jPanel2, new TaiKhoan_BUS().xoaTK(tk));
				jTable1.setModel(new javax.swing.table.DefaultTableModel(
		            update(),
		            new String [] {
		            		"Tên đăng nhập","Mật khẩu","Phân quyền"
		            }
		        ));
		        model.addElement(tenDN);
    		}
    	}
    	else
    		JOptionPane.showMessageDialog(jPanel2, "Chọn một tài khoản để sửa !","Error",0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void jTextField1KeyListener(java.awt.event.KeyEvent evt ){
    	String search = String.valueOf(comboBox_1.getItemAt(comboBox_1.getSelectedIndex()));
    	String s = jTextField1.getText();
    	if( search.equals("Tên đăng nhập") ) {
    		ArrayList<TaiKhoan> list = new TaiKhoan_BUS().timTK_TenDN(s);
    		Object data[][] = new Object [list.size()][3];
    		for( int i=0 ; i<list.size() ; i++ ) {
    			data[i][0] = list.get(i).getTenDN();
            	data[i][1] = list.get(i).getMatKhau();
            	if( list.get(i).getPhanQuyen().equals("Quanly") )
            		data[i][2] = "Quản lý";
            	else
            		data[i][2] = "Nhân viên";
    		}
    		jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            data,
	            new String [] {
	            		"Tên đăng nhập","Mật khẩu","Phân quyền"
	            }
	        ));
    	}
    	else {
    		ArrayList<TaiKhoan> list = new TaiKhoan_BUS().timTK_PhanQuyen(s);
    		Object data[][] = new Object [list.size()][3];
    		for( int i=0 ; i<list.size() ; i++ ) {
    			data[i][0] = list.get(i).getTenDN();
            	data[i][1] = list.get(i).getMatKhau();
            	if( list.get(i).getPhanQuyen().equals("Quanly") )
            		data[i][2] = "Quản lý";
            	else
            		data[i][2] = "Nhân viên";
    		}
    		jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            data,
	            new String [] {
	            	"Tên đăng nhập","Mật khẩu","Phân quyền"
	            }
	        ));
    		
    	}
    }
    
    public Object[][] update() {
    	int n = new TaiKhoan_BUS().getListTaiKhoan().size();
    	List<TaiKhoan> list = new TaiKhoan_BUS().getListTaiKhoan2();
    	Object[][] data = new Object[n][3];
        for( int i=0 ; i<n ; i++ ) {
        	data[i][0] = list.get(i).getTenDN();
        	data[i][1] = list.get(i).getMatKhau();
        	if( list.get(i).getPhanQuyen().equals("Quanly") )
        		data[i][2] = "Quản lý";
        	else
        		data[i][2] = "Nhân viên";
        }
        return data;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTaiKhoan(NV).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpKho;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpThanhTieuDe;
    private javax.swing.JLabel lbTimKiem;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblBanHang1;
    private javax.swing.JLabel lblBanHang2;
    private javax.swing.JLabel lblBanHang3;
    private javax.swing.JLabel lblBanHang4;
    private javax.swing.JLabel lblBanHang5;
    private javax.swing.JLabel lblBanHang6;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblKhoHang;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNhapHang;
    private JTextField textField;
    private JTextField textField_1;
    private JComboBox comboBox;
    private JComboBox comboBox_1;
    private JLabel lblNewLabel_3;
    private JLabel lblNewLabel_4;
    private JLabel lblNewLabel_5;
    private JComboBox comboBox_2;
    private JTextField textField_2;
    private JComboBox comboBox_3;
    private DefaultComboBoxModel<String> model;
}
